---

- name: Minha primeira playbook
  hosts: all
  vars: 
   - username: sysadim
  tasks: 
   - name: adicionando usuario
     user:
       name: "{{username}}"
       state:  present 
   - name: isntalando o vim em todas as maquinas
     package: 
      name:  
       - vim
       - cowsay
       - sl
       - figlet 
      state: present
      update_cache: yes
     ignore_errors: yes
 
